import type { NextConfig } from 'next'
import createNextIntlPlugin from 'next-intl/plugin'
import { getClerkFrontendApiHost } from './lib/clerk-frontend-api'

const withNextIntl = createNextIntlPlugin('./lib/i18n/request.ts')

const clerkFrontendApiHost = getClerkFrontendApiHost(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)

if (!clerkFrontendApiHost) {
  throw new Error(
    'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is missing or malformed — cannot derive the Clerk ' +
      'Frontend API host for the Content-Security-Policy. Set a valid pk_test_*/pk_live_* key.',
  )
}

const CLERK_FAPI = `https://${clerkFrontendApiHost}`
// Clerk's bot/abuse-protection challenge origin — fixed across every key,
// not derived from the publishable key. See @clerk/nextjs's own CSP
// default (node_modules/@clerk/nextjs/dist/esm/server/content-security-policy.js).
const CLERK_PROTECT = 'https://*.protect.clerk.com'
// Vercel Blob (`@vercel/blob`'s `put()` in lib/server/uploads-service.ts and
// lib/server/tables-service.ts): public object URLs are served from
// *.public.blob.vercel-storage.com and rendered directly via <img src> in
// components/landing/*.
const VERCEL_BLOB = 'https://*.public.blob.vercel-storage.com'
const isDev = process.env.NODE_ENV !== 'production'

/**
 * Content-Security-Policy — hand-maintained here rather than generated by
 * `clerkMiddleware()`'s `contentSecurityPolicy` option (middleware.ts).
 * That option can only ADD to Clerk's own default directives, never narrow
 * or remove one, and Clerk's non-strict default `script-src` includes a
 * bare `https:`/`http:` scheme wildcard — allowing a script from literally
 * any HTTP(S) origin, which defeats the point of restricting `script-src`
 * at all. `strict: true` would drop the wildcard but requires threading a
 * nonce through every response, which breaks this app's SSG pages — a
 * separate, larger change, not done here.
 *
 * `'unsafe-inline'` on script-src is still required: the Next.js App
 * Router streams RSC payloads via inline
 * `<script>self.__next_f.push([...])</script>` tags with no nonce wired up.
 *
 * The Clerk Frontend API host is derived from the active publishable key
 * (see `getClerkFrontendApiHost` in `lib/clerk-frontend-api.ts`) rather than hardcoded, so this
 * same static header is correct for both a dev (`pk_test_*`) and a
 * production (`pk_live_*`) key.
 */
const CSP_DIRECTIVES: Record<string, string[]> = {
  'default-src': ["'self'"],
  'script-src': [
    "'self'",
    "'unsafe-inline'",
    ...(isDev ? ["'unsafe-eval'"] : []),
    CLERK_FAPI,
    CLERK_PROTECT,
  ],
  'connect-src': ["'self'", CLERK_FAPI, CLERK_PROTECT],
  'frame-src': [CLERK_PROTECT],
  'img-src': ["'self'", 'data:', VERCEL_BLOB],
  'font-src': ["'self'", 'data:', 'https://fonts.gstatic.com'],
  'style-src': ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'],
  'worker-src': ["'self'", 'blob:'],
  'base-uri': ["'self'"],
  'frame-ancestors': ["'none'"],
  'object-src': ["'none'"],
}

const CONTENT_SECURITY_POLICY = Object.entries(CSP_DIRECTIVES)
  .map(([directive, sources]) => `${directive} ${sources.join(' ')}`)
  .join('; ')

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'X-DNS-Prefetch-Control', value: 'on' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
          { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains' },
          { key: 'Content-Security-Policy', value: CONTENT_SECURITY_POLICY },
        ],
      },
    ]
  },
}

export default withNextIntl(nextConfig)
