import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: {
          DEFAULT: 'rgb(var(--background-rgb) / <alpha-value>)',
          secondary: 'rgb(var(--background-secondary-rgb) / <alpha-value>)',
          surface: 'rgb(var(--background-surface-rgb) / <alpha-value>)',
        },
        foreground: 'rgb(var(--foreground-rgb) / <alpha-value>)',
        card: {
          DEFAULT: 'rgb(var(--card-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--card-foreground-rgb) / <alpha-value>)',
        },
        popover: {
          DEFAULT: 'rgb(var(--popover-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--popover-foreground-rgb) / <alpha-value>)',
        },
        primary: {
          DEFAULT: 'rgb(var(--primary-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--primary-foreground-rgb) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--secondary-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--secondary-foreground-rgb) / <alpha-value>)',
        },
        muted: {
          DEFAULT: 'rgb(var(--muted-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--muted-foreground-rgb) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--accent-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--accent-foreground-rgb) / <alpha-value>)',
        },
        destructive: {
          DEFAULT: 'rgb(var(--destructive-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--destructive-foreground-rgb) / <alpha-value>)',
        },
        border: 'rgb(var(--border-rgb) / <alpha-value>)',
        input: 'rgb(var(--input-rgb) / <alpha-value>)',
        ring: 'rgb(var(--ring-rgb) / <alpha-value>)',
        gold: {
          50: '#FFF9E6', 100: '#FFF0BF', 200: '#FFE080', 300: '#FFD040',
          400: '#FFBF00', 500: '#C9A84C', 600: '#A07830', 700: '#7A5820',
          800: '#543B10', 900: '#2E1E00',
        },
        emerald: {
          DEFAULT: '#2D8653',
          light: '#3DAA6A',
          dark: '#1E5C39',
        },
        crimson: {
          DEFAULT: '#8B2635',
          light: '#B03344',
          dark: '#5C1A25',
        },
        arcane: {
          DEFAULT: '#4A1C8B',
          light: '#6428B8',
          dark: '#310F5E',
        },
        // Stitch "Alea dos" design system colors
        'inverse-surface': '#e5e2e1',
        'outline': '#a08d80',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d8c3b4',
        'surface-container-high': '#2a2a2a',
        'on-primary': '#4d2700',
        'surface-container-highest': '#353534',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'tertiary': '#cac99f',
        'on-background': '#e5e2e1',
        'error': '#ffb4ab',
        'surface': '#131313',
        'surface-variant': '#353534',
        'outline-variant': '#524439',
        'surface-container-low': '#1c1b1b',
        'primary-container': '#c8803f',
        'secondary-container': '#5a403f',
        'surface-container': '#201f1f',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-container': '#ffdcc2',
        'on-secondary': '#422020',
        'on-secondary-container': '#ffdad8',
        'on-tertiary': '#333200',
        'tertiary-container': '#4a4900',
        'on-tertiary-container': '#e6e58a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'scrim': '#000000',
        'shadow': '#000000',
        'primary-fixed': '#ffdcc2',
        'primary-fixed-dim': '#ffb77b',
        'on-primary-fixed': '#2d1200',
        'on-primary-fixed-variant': '#c8803f',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#e2bebb',
        'on-secondary-fixed': '#2c1514',
        'on-secondary-fixed-variant': '#5a403f',
        'tertiary-fixed': '#e6e58a',
        'tertiary-fixed-dim': '#cac99f',
        'on-tertiary-fixed': '#1e1d00',
        'on-tertiary-fixed-variant': '#4a4900',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#8c4a00',
        alea: {
          bg: '#0d1218',
          bg2: '#131922',
          ink: '#f4ead5',
          gold: '#c8a25b',
          gold2: '#e6c281',
          ruby: '#a93232',
          teal: '#5fb3d4',
        },
      },
      fontFamily: {
        cinzel: ['Cinzel', 'serif'],
        inter: ['Inter', 'sans-serif'],
        crimson: ['Crimson Text', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.0625rem',
        md: '0.1875rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        // full is not overridden → keeps Tailwind default (9999px)
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        shimmer: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        glow: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
        'dice-roll': {
          '0%':   { transform: 'rotate(0deg) scale(1)' },
          '25%':  { transform: 'rotate(90deg) scale(1.08)' },
          '50%':  { transform: 'rotate(180deg) scale(1)' },
          '75%':  { transform: 'rotate(270deg) scale(1.08)' },
          '100%': { transform: 'rotate(360deg) scale(1)' },
        },
        'mod-pulse': { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.4', transform: 'scale(0.8)' } },
        'mod-marq': { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        'mod-float': { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shimmer: 'shimmer 2s infinite',
        glow: 'glow 2s ease-in-out infinite',
        'dice-roll': 'dice-roll 1.2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'mod-pulse': 'mod-pulse 1.6s infinite',
        'mod-marq': 'mod-marq 38s linear infinite',
        'mod-float': 'mod-float 5s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
export default config
