-- Documents the invariant (#377) that "event_room_blocks"."table_id", when
-- non-null, must belong to the room identified by that row's "room_id" —
-- i.e. "tables"."room_id" for that table id must equal "room_id" above.
--
-- There is no DB-level CHECK or trigger enforcing this: a plain CHECK
-- constraint can't reference another table, and a constraint trigger's
-- correctness can't be verified without executing and testing it against a
-- live database (out of scope here — see issue #377 for that tradeoff).
-- It is enforced only in application code, in
-- applyClubEventBlocksAndMaterials() (lib/server/club-events-service.ts).
-- Any future insert path into "event_room_blocks" that bypasses that guard
-- could silently violate the invariant.
--
-- This is a prepared-but-unexecuted migration file, per this project's "agent
-- prepares, user applies" DB rule (see CLAUDE.md) — it must be run manually
-- with scripts/apply-neon-schema.mjs, same as every other file here.
--
-- Added as a new file rather than edited into 009_event_room_blocks.sql:
-- apply-neon-schema.mjs keeps a SHA-256 checksum of each schema file's raw
-- text and hard-aborts with "Schema drift detected" if an already-applied
-- file's content changes. A COMMENT ON COLUMN is also actual DDL (visible in
-- \d+ output), unlike a "--" line comment, which splitStatements() strips
-- before anything reaches Postgres and would therefore never have reached
-- the database at all.
--
-- Collision risk: Postgres stores exactly one comment per column
-- (a single pg_description row) — a later COMMENT ON COLUMN on this same
-- column silently replaces this one, it does not append. Open issue #379
-- targets this same "table_id" column with its own COMMENT ON COLUMN for a
-- different fact (what a null table_id means). Whichever of #377/#379 is
-- applied second must restate this invariant's text alongside its own, or
-- fold both into one combined COMMENT ON COLUMN statement — otherwise the
-- other's fact is lost from the live database with no trace on disk or in
-- the checksum ledger.

COMMENT ON COLUMN "event_room_blocks"."table_id" IS
  'Invariant (#377): when non-null, must belong to this row''s room_id — i.e. tables.room_id for this table id must equal room_id above. Enforced only in application code (applyClubEventBlocksAndMaterials() in lib/server/club-events-service.ts) — no DB-level CHECK/trigger, since a plain CHECK can''t reference another table. Any insert path bypassing that guard could silently violate it.';
