/**
 * Single source of truth for business-logic error code strings.
 *
 * Values MUST remain identical to their string literals — client-side switch
 * statements compare against these strings directly and must not be touched
 * when refactoring server code.
 */
export const ERROR_CODES = {
  // Reservation / availability
  SLOT_TAKEN: 'SLOT_TAKEN',
  BOOKING_WINDOW_EXCEEDED: 'BOOKING_WINDOW_EXCEEDED',
  CANCELLATION_CUTOFF: 'CANCELLATION_CUTOFF',
  USER_ALREADY_HAS_RESERVATION_IN_SLOT: 'USER_ALREADY_HAS_RESERVATION_IN_SLOT',
  STATUS_TRANSITION_FORBIDDEN: 'STATUS_TRANSITION_FORBIDDEN',
  ROOM_BLOCKED_BY_EVENT: 'ROOM_BLOCKED_BY_EVENT',

  // Check-in
  CHECK_IN_ALREADY_ACTIVE: 'CHECK_IN_ALREADY_ACTIVE',
  CHECK_IN_NO_RESERVATION: 'CHECK_IN_NO_RESERVATION',
  CHECK_IN_TOO_EARLY: 'CHECK_IN_TOO_EARLY',
  CHECK_IN_TOO_LATE: 'CHECK_IN_TOO_LATE',

  // Equipment
  EQUIPMENT_ALREADY_RESERVED: 'EQUIPMENT_ALREADY_RESERVED',
  EQUIPMENT_LOCKED_TO_ANOTHER_ROOM: 'EQUIPMENT_LOCKED_TO_ANOTHER_ROOM',
  INVALID_ROOM_EQUIPMENT: 'INVALID_ROOM_EQUIPMENT',

  // Saved games
  SAVED_GAME_ALREADY_RENEWED: 'SAVED_GAME_ALREADY_RENEWED',
  SAVED_GAME_BOTTOM_RESERVATION_CONFLICT: 'SAVED_GAME_BOTTOM_RESERVATION_CONFLICT',
  SAVED_GAME_BOTTOM_RESERVED: 'SAVED_GAME_BOTTOM_RESERVED',
  SAVED_GAME_CONFLICT: 'SAVED_GAME_CONFLICT',
  SAVED_GAME_EVENT_CONFLICT: 'SAVED_GAME_EVENT_CONFLICT',
  SAVED_GAME_INVALID_RANGE: 'SAVED_GAME_INVALID_RANGE',
  SAVED_GAME_MAX_DURATION: 'SAVED_GAME_MAX_DURATION',
  SAVED_GAME_NOT_ACTIVE: 'SAVED_GAME_NOT_ACTIVE',
  SAVED_GAME_RENEWAL_NOT_OPEN: 'SAVED_GAME_RENEWAL_NOT_OPEN',
  SAVED_GAME_REQUIRES_REMOVABLE_TOP: 'SAVED_GAME_REQUIRES_REMOVABLE_TOP',
  SAVED_GAME_START_IN_PAST: 'SAVED_GAME_START_IN_PAST',

  // Auth (activation / recovery / session) — #313 smoke QA: these used to be
  // hardcoded English sentences reaching the Spanish UI raw. Client
  // components map each code to a translated message (messages/*.json,
  // `auth.errors.*`); see `lib/auth/service-error-messages.ts`.
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_ONLY_MEMBER_CAN_ACTIVATE: 'AUTH_ONLY_MEMBER_CAN_ACTIVATE',
  AUTH_MEMBER_ALREADY_ACTIVE: 'AUTH_MEMBER_ALREADY_ACTIVE',
  AUTH_ONLY_MEMBER_CAN_RECEIVE_RECOVERY: 'AUTH_ONLY_MEMBER_CAN_RECEIVE_RECOVERY',
  AUTH_MEMBER_MUST_ACTIVATE_BEFORE_RECOVERY: 'AUTH_MEMBER_MUST_ACTIVATE_BEFORE_RECOVERY',
  AUTH_INVALID_ACTIVATION_LINK: 'AUTH_INVALID_ACTIVATION_LINK',
  AUTH_ACTIVATION_LINK_EXPIRED: 'AUTH_ACTIVATION_LINK_EXPIRED',
  AUTH_ACTIVATION_LINK_USED: 'AUTH_ACTIVATION_LINK_USED',
  AUTH_ACCOUNT_CREDENTIALS_CREATE_FAILED: 'AUTH_ACCOUNT_CREDENTIALS_CREATE_FAILED',
  AUTH_PASSWORD_REJECTED: 'AUTH_PASSWORD_REJECTED',
  AUTH_PASSWORD_REJECTED_GENERIC: 'AUTH_PASSWORD_REJECTED_GENERIC',
  AUTH_ACTIVATION_FAILED: 'AUTH_ACTIVATION_FAILED',
  AUTH_INVALID_RECOVERY_LINK: 'AUTH_INVALID_RECOVERY_LINK',
  AUTH_RECOVERY_LINK_EXPIRED: 'AUTH_RECOVERY_LINK_EXPIRED',
  AUTH_RECOVERY_LINK_USED: 'AUTH_RECOVERY_LINK_USED',
  AUTH_INTERNAL_ERROR: 'AUTH_INTERNAL_ERROR',
  AUTH_ACCOUNT_CREDENTIALS_UPDATE_FAILED: 'AUTH_ACCOUNT_CREDENTIALS_UPDATE_FAILED',
  AUTH_RECOVERY_FAILED: 'AUTH_RECOVERY_FAILED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

/**
 * Union of just the `AUTH_*` error codes. Lets `service-error-messages.ts`
 * type its message map as `Record<AuthErrorCode, string>` instead of
 * `Partial<Record<string, string>>`, so adding a new `AUTH_*` code with no
 * matching translation-key entry is a compile error, not a silent gap only
 * the dedicated test file happens to catch (#313 code-review finding 8).
 */
type AuthErrorCodeKey = Extract<keyof typeof ERROR_CODES, `AUTH_${string}`>
export type AuthErrorCode = (typeof ERROR_CODES)[AuthErrorCodeKey]
